import { TaskAssignmentService } from '../helpers/taskAssignmentService';
import { TaskRepository } from '../repositories/taskRepository';
import { ActivityLogService } from '../services/activityLogServices';
import userServices from '../services/userServices';
import { TaskDomainService } from '../helpers/taskDomainService';
import taskServices from '../services/taskServices';
import { UserRepository } from '../repositories/userRepository';
import { ActivityLogRepository } from '../repositories/activityLogRepository';
import { ActivityLogHelper } from '../helpers/activityLogHelper';
import { notificationService } from './notificationServiceContainer';
import { NotificationHelper } from '../helpers/notificationHelper';

const activityrepository=new ActivityLogRepository();
const userrepository=new UserRepository();
const assignment=new TaskAssignmentService(userrepository);
const repository=new TaskRepository();
const activitylogservice=new ActivityLogService(activityrepository);
const activitylog=new ActivityLogHelper(activitylogservice);
const taskdomain=new TaskDomainService();
const notificationhelper=new NotificationHelper(notificationService);
export const taskservice = new taskServices(repository,assignment,activitylog,taskdomain,notificationhelper);